#!/usr/bin/env node
/* ============================================================================
 * dsh-unidoc — client bundle builder
 *
 * 把动态 client 源码 src/client.js（`return {...}` 函数体）静态化为浏览器
 * bundle lib/client.js：以 window.__ModuleLoader__.load({id, factory}) 标准格式
 * 交付（与 dsh-web-ui 全家桶静态插件一致），并把动态插件的全局符号桥接到
 * 静态 client 环境：
 *
 *   React           → ModuleLoader 的 require("react")
 *   styles.insert   → 自管 <style> 标签（data-unidoc 标记，卸载时移除）
 *   host.call       → fetch POST /api/dsh-unidoc/rpc
 *   timer.timeout   → window.setTimeout 包装（返回 disposer）
 *   ctx.get(name)   → 静态 ctx 的注入服务（slots / timer）
 *   ctx.effect(fn)  → 静态 ctx.effect（Cordis 标准）
 *
 * 用法：node scripts/build-client.mjs
 * 产物：lib/client.js（无外部依赖，直接可被 DSH web 加载）
 * ========================================================================== */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), '..')
const SOURCE = fs.readFileSync(path.join(ROOT, 'src', 'client.js'), 'utf8')
const OUT = path.join(ROOT, 'lib', 'client.js')

// 源码包进 async 函数体执行（与 DSH define-time 预检 / check.js 同构），
// 再经 JSON.stringify 序列化成字符串字面量，运行期 eval 执行 —— 规避源码内
// 反引号 / ${} / 引号对外层代码的干扰。
const BODY = `(async () => {\n${SOURCE}\n})()`
const RUN_LITERAL = JSON.stringify(BODY)

const BUNDLE = `/* dsh-unidoc — client half (static bundle, generated by scripts/build-client.mjs) */
window.__ModuleLoader__.load({
  id: 'dsh-unidoc',
  factory: (require) => {
    var module = { exports: {} };
    var exports = module.exports;
    Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });

    const React = require('react');

    /* ---- styles 桥接：自管 <style> 标签（动态 runner 的 styles.insert 等价物） ---- */
    const styles = {
      insert(css) {
        if (typeof css !== 'string') throw new Error('styles.insert(css) needs a CSS string');
        const tag = document.createElement('style');
        tag.dataset.unidoc = '1';
        tag.textContent = css;
        document.head.append(tag);
        return () => { tag.remove(); };
      },
      dispose() {
        document.querySelectorAll('style[data-unidoc]').forEach((tag) => tag.remove());
      },
    };

    /* ---- host 桥接：RPC → HTTP（host 端 lib/index.js 注册的 /api/dsh-unidoc/rpc） ---- */
    const host = {
      async call(method, args) {
        let response;
        try {
          response = await fetch('/api/dsh-unidoc/rpc', {
            method: 'POST',
            headers: { 'content-type': 'application/json' },
            body: JSON.stringify({ method, args: args === void 0 ? undefined : args }),
          });
        } catch (error) {
          throw new Error('unidoc rpc transport failed: ' + (error && error.message ? error.message : String(error)));
        }
        let payload;
        try { payload = await response.json(); }
        catch (error) {
          throw new Error('unidoc rpc bad response (' + response.status + '): ' + (error && error.message ? error.message : String(error)));
        }
        if (payload && payload.ok === false) {
          throw new Error('unidoc.' + method + ' failed: ' + (payload.error || 'unknown error'));
        }
        return payload;
      },
    };

    /* ---- timer 桥接：setTimeout 包装（返回 disposer，与 timer.timeout 同形） ---- */
    const timer = {
      timeout(fn, ms) {
        const id = window.setTimeout(fn, ms);
        return () => window.clearTimeout(id);
      },
    };

    /* ---- 执行动态源码（闭包注入 React / styles / host / timer / console） ---- */
    const runner = new Function(
      'React', 'styles', 'host', 'timer', 'console',
      'const __run = ' + ${RUN_LITERAL} + ';\\nreturn eval(__run);'
    );

    let pluginPromise;
    const getPlugin = () => {
      if (!pluginPromise) {
        pluginPromise = Promise.resolve().then(() => runner(React, styles, host, timer, console)).then((plugin) => {
          if (!plugin || typeof plugin.apply !== 'function') {
            throw new Error('dsh-unidoc: client source did not return a plugin object');
          }
          return plugin;
        });
      }
      return pluginPromise;
    };

    /* ---- 静态插件入口：apply(ctx) 里桥接动态 ctx 假面 ---- */
    const inject = ['slots'];

    function apply(ctx) {
      const fakeCtx = {
        get(name) {
          // 优先转发真实 ctx 服务（slots / timer / sessions 等都由 DSH 客户端
          // 运行时提供，含 rootCtx.reflect.provide 的 sessions 服务——Client 借此
          // 读取「当前选中会话」的工作区 cwd，作为 unidoc.root 的 hintCwd 权威信号）；
          // timer 在真实服务缺失时回退到桥接实现
          const value = ctx[name];
          if (value !== void 0) return value;
          if (name === 'timer') return timer;
          return void 0;
        },
        effect(fn, label) {
          return ctx.effect(fn, label);
        },
      };
      return getPlugin().then((plugin) => {
        const result = plugin.apply(fakeCtx);
        return result === void 0 ? undefined : result;
      });
    }

    exports.apply = apply;
    exports.inject = inject;
    return module.exports;
  }
});
`

fs.mkdirSync(path.join(ROOT, 'lib'), { recursive: true })
fs.writeFileSync(OUT, BUNDLE, 'utf8')
console.log('OK   lib/client.js (' + BUNDLE.length + ' chars)')
